### ISSUE TITLE
Swig command and Python 3 compatibility

### ISSUE THREAD

**Issue by kevd42** [samuelstjean/spams-python#1]
Hi,
What command (what options to swig) did you use to re-generate the swig interfaces? I'm trying to port them to Python 3 using swig 3.0.8 but I can't figure out what I should use. Do you have a *.i file ?

EDIT: Never-mind, I found it on the other branch. After a few tweaks, it's finally working. If you want me to contribute, I can give you the new dist with the modified files. The steps I followed were:
- use `2to3` to modify the .py and .py.in files (+ changing the path to python and numpy in setup.py.in and mkpy)
- modify numpi.i to add

`%#if PY_MAJOR_VERSION < 3`

```
if (PyFile_Check(    py_obj)) return "file"        ;

if (PyInstance_Check(py_obj)) return "instance"    ;
```

`%#endif`
- modify py_typemaps.i to replace
  `# ARGOUT` by `// ARGOUT`
  `# test argout` by `// test argout`
  `# argout in` by `// argout in`
- add missing parentheses in linalg.h.
  And I think that's it. So I launched mkdist then followed the normal install procedure in the generated dist.
  Spams seems to work on my python3 but I haven't extensively tested it yet.

**Comment by samuelstjean** [comment]
Yep, I just did a plain rehost of the source distribution files themselves here and cloned the svn on another branch, which does give you everything to generate the stuff with swig. Indeed as you have discovered, some changes are needed to the code and setup.py to make it truly work, which I did not put them as I did a clean unpatched rehost.

I guess I should put them, I mostly use this as a source in another project requirements.txt for easy building. I also have a python3 zip source I did if you want here https://github.com/samuelstjean/spams-python/releases/download/0.1/spams-python-v2.5-python3.zip (it also has patches for gcc 6), which are taken form the Arch user repository https://aur.archlinux.org/packages/python-spams-svn/

Here is the archive with the mentioned patches, the PKGBUILD file is a fancy bash script which applies them and build everything for you https://aur.archlinux.org/cgit/aur.git/snapshot/python-spams-svn.tar.gz

Finally, someone is trying to get spams to build by fetching the right numpy blas library so the setup.py would now be cleaner over here https://github.com/conda-forge/python-spams-feedstock/pull/1
