### ISSUE TITLE
ERROR: FAILED when importing SCILPY library

### ISSUE THREAD

**Issue by Troudi-Abir** [samuelstjean/spams-python#13]
Dear all,
I'm trying importing scilpy library on jupyter notebook and I get the following error with the following command ; "pip install scilpy"
Any help please ??
Collecting scilpy
  Using cached scilpy-0.2.dev0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: dipy>=1.1.0 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (1.4.0)
Requirement already satisfied: cycler==0.10.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (0.10.0)
Collecting Pillow==6.2.*
  Using cached Pillow-6.2.2-cp36-cp36m-win_amd64.whl (2.0 MB)
Collecting requests==2.23.*
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting future==0.17.*
  Using cached future-0.17.1-py3-none-any.whl
Collecting nilearn==0.6.*
  Using cached nilearn-0.6.2-py3-none-any.whl (2.5 MB)
Requirement already satisfied: six==1.15.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (1.15.0)
Collecting h5py==2.9.*
  Using cached h5py-2.9.0-cp36-cp36m-win_amd64.whl (2.4 MB)
Requirement already satisfied: vtk==8.1.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (8.1.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy==1.18.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (1.18.5)
Requirement already satisfied: pyparsing==2.2.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (2.2.2)
Requirement already satisfied: pytz==2018.4.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (2018.4)
Collecting coloredlogs==10.0.*
  Using cached coloredlogs-10.0-py2.py3-none-any.whl (47 kB)
Collecting statsmodels==0.11.*
  Using cached statsmodels-0.11.1-cp36-none-win_amd64.whl (8.2 MB)
Collecting bz2file==0.98.*
  Using cached bz2file-0.98-py3-none-any.whl
Collecting dmri-commit==1.3.*
  Using cached dmri-commit-1.3.9.4.tar.gz (681 kB)
Collecting pybids==0.10.*
  Using cached pybids-0.10.2-py2.py3-none-any.whl (3.1 MB)
Collecting matplotlib==2.2.*
  Using cached matplotlib-2.2.5-cp36-cp36m-win_amd64.whl (9.0 MB)
Collecting pytest-console-scripts==0.2.*
  Using cached pytest_console_scripts-0.2.0-py3-none-any.whl
Requirement already satisfied: scipy==1.4.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (1.4.1)
Collecting openpyxl==2.6.*
  Using cached openpyxl-2.6.4-py2.py3-none-any.whl
Collecting googledrivedownloader==0.*
  Using cached googledrivedownloader-0.4-py2.py3-none-any.whl (3.9 kB)
Requirement already satisfied: nibabel==3.0.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (3.0.2)
Collecting bctpy==0.5.*
  Using cached bctpy-0.5.2-py3-none-any.whl (102 kB)
Requirement already satisfied: Cython==0.29.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (0.29.22)
Collecting python-dateutil==2.7.*
  Using cached python_dateutil-2.7.5-py2.py3-none-any.whl (225 kB)
Collecting pytest==5.3.*
  Using cached pytest-5.3.5-py3-none-any.whl (235 kB)
Collecting kiwisolver==1.0.*
  Using cached kiwisolver-1.0.1-cp36-none-win_amd64.whl (57 kB)
Requirement already satisfied: setuptools==46.1.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (46.1.3)
Requirement already satisfied: scikit-learn==0.22.* in c:\programdata\anaconda3\envs\python3\lib\site-packages (from scilpy) (0.22.2.post1)
Collecting fury==0.2.*
  Using cached fury-0.2.0-py3-none-any.whl (140 kB)
Collecting trimeshpy==0.0.*
  Using cached trimeshpy-0.0.2-py3-none-any.whl
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\python3\lib\site-packages (from coloredlogs==10.0.*->scilpy) (0.4.4)
Collecting humanfriendly>=4.7
  Using cached humanfriendly-9.1-py2.py3-none-any.whl (86 kB)
Collecting dmri-amico>=1.2.3
  Using cached dmri_amico-1.2.9-py3-none-any.whl
Requirement already satisfied: joblib>=0.11 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from nilearn==0.6.*->scilpy) (1.0.1)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Collecting et-xmlfile
  Using cached et_xmlfile-1.0.1-py3-none-any.whl
Collecting jdcal
  Using cached jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Collecting pandas>=0.23
  Using cached pandas-1.1.5-cp36-cp36m-win_amd64.whl (8.7 MB)
Collecting num2words
  Using cached num2words-0.5.10-py3-none-any.whl (101 kB)
Collecting bids-validator
  Using cached bids_validator-1.6.0-py2.py3-none-any.whl (15 kB)
Collecting sqlalchemy
  Using cached SQLAlchemy-1.4.5-cp36-cp36m-win_amd64.whl (1.5 MB)
Collecting patsy
  Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)
Collecting more-itertools>=4.0.0
  Using cached more_itertools-8.7.0-py3-none-any.whl (48 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\envs\python3\lib\site-packages (from pytest==5.3.*->scilpy) (20.9)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\envs\python3\lib\site-packages (from pytest==5.3.*->scilpy) (0.2.5)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from pytest==5.3.*->scilpy) (20.3.0)
Requirement already satisfied: importlib-metadata>=0.12 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from pytest==5.3.*->scilpy) (3.7.3)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting py>=1.5.0
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting mock>=2.0.0
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting pytest-runner
  Using cached pytest_runner-5.3.0-py3-none-any.whl (7.1 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from requests==2.23.*->scilpy) (2020.12.5)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: tqdm>=4.29.0 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from trimeshpy==0.0.*->scilpy) (4.59.0)
Collecting python-spams>=2.6.1
  Using cached python-spams-2.6.1.11.tar.gz (1.6 MB)
Collecting pyreadline
  Using cached pyreadline-2.1-py3-none-any.whl
Requirement already satisfied: zipp>=0.5 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from importlib-metadata>=0.12->pytest==5.3.*->scilpy) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from importlib-metadata>=0.12->pytest==5.3.*->scilpy) (3.7.4.3)
Collecting docopt>=0.6.2
  Using cached docopt-0.6.2-py2.py3-none-any.whl
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\envs\python3\lib\site-packages (from sqlalchemy->pybids==0.10.*->scilpy) (1.0.0)
Building wheels for collected packages: dmri-commit, python-spams
  Building wheel for dmri-commit (setup.py): started
  Building wheel for dmri-commit (setup.py): finished with status 'error'
  Running setup.py clean for dmri-commit
  Building wheel for python-spams (setup.py): started
  Building wheel for python-spams (setup.py): finished with status 'error'
  Running setup.py clean for python-spams
Failed to build dmri-commit python-spams
Installing collected packages: Pillow, h5py, python-spams, python-dateutil, pyreadline, py, pluggy, more-itertools, docopt, atomicwrites, urllib3, sqlalchemy, sklearn, pytest-runner, pytest, patsy, pandas, num2words, mock, kiwisolver, jdcal, idna, humanfriendly, et-xmlfile, dmri-amico, chardet, bids-validator, trimeshpy, statsmodels, requests, pytest-console-scripts, pybids, openpyxl, nilearn, matplotlib, googledrivedownloader, future, fury, dmri-commit, coloredlogs, bz2file, bctpy, scilpy
  Attempting uninstall: Pillow
    Found existing installation: Pillow 7.1.2
    Uninstalling Pillow-7.1.2:
      Successfully uninstalled Pillow-7.1.2
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
    Running setup.py install for python-spams: started
    Running setup.py install for python-spams: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\python3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-jvbotbai'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m0a4oobw\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\commit
  copying commit\models.py -> build\lib.win-amd64-3.6\commit
  copying commit\solvers.py -> build\lib.win-amd64-3.6\commit
  copying commit\__init__.py -> build\lib.win-amd64-3.6\commit
  creating build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\config.py -> build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\__init__.py -> build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\operator.c -> build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\operator.pyx -> build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\operator.pyxbld -> build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\operator_noLUT.c -> build\lib.win-amd64-3.6\commit\operator
  copying commit\operator\operator_withLUT.c -> build\lib.win-amd64-3.6\commit\operator
  running build_ext
  Compiling commit/trk2dictionary/trk2dictionary.pyx because it depends on C:\ProgramData\Anaconda3\envs\python3\lib\site-packages\Cython\Includes\numpy\__init__.pxd.
  Compiling commit/core.pyx because it changed.
  Compiling commit/proximals.pyx because it depends on C:\ProgramData\Anaconda3\envs\python3\lib\site-packages\Cython\Includes\numpy\__init__.pxd.
  [1/3] Cythonizing commit/core.pyx
  [2/3] Cythonizing commit/proximals.pyx
  [3/3] Cythonizing commit/trk2dictionary/trk2dictionary.pyx
  warning: commit\trk2dictionary\trk2dictionary.pyx:179:44: Index should be typed for more efficient access
  building 'commit.trk2dictionary' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\Release
  creating build\temp.win-amd64-3.6\Release\Release\commit
  creating build\temp.win-amd64-3.6\Release\Release\commit\trk2dictionary
  D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icommit/trk2dictionary -IC:\ProgramData\Anaconda3\envs\python3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\envs\python3\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpcommit/trk2dictionary/trk2dictionary.cpp /Fobuild\temp.win-amd64-3.6\Release\Release\commit/trk2dictionary/trk2dictionary.obj -w
  cl : Command line warning D9025 : overriding '/W3' with '/w'
  trk2dictionary.cpp
  c:\programdata\anaconda3\envs\python3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  c:\users\administrateur\appdata\local\temp\pip-install-m0a4oobw\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\commit\trk2dictionary\trk2dictionary_c.cpp(252): error C2131: expression did not evaluate to a constant
  c:\users\administrateur\appdata\local\temp\pip-install-m0a4oobw\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\commit\trk2dictionary\trk2dictionary_c.cpp(252): note: failure was caused by a read of a variable outside its lifetime
  c:\users\administrateur\appdata\local\temp\pip-install-m0a4oobw\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\commit\trk2dictionary\trk2dictionary_c.cpp(252): note: see usage of 'Np'
  c:\users\administrateur\appdata\local\temp\pip-install-m0a4oobw\dmri-commit_4fdde645d0d345e48bf1dbd7a428c1e7\commit\trk2dictionary\trk2dictionary_c.cpp(273): error C3863: array type 'float [Np]' is not assignable
  error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for dmri-commit
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\python3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\python-spams_31de6775be654c6691f857d4fb6a5893\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\python-spams_31de6775be654c6691f857d4fb6a5893\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-ct929ule'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m0a4oobw\python-spams_31de6775be654c6691f857d4fb6a5893\
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\myscipy_rand
  copying myscipy_rand\myscipy_rand.py -> build\lib.win-amd64-3.6\myscipy_rand
  copying myscipy_rand\__init__.py -> build\lib.win-amd64-3.6\myscipy_rand
  creating build\lib.win-amd64-3.6\spams
  copying spams\spams.py -> build\lib.win-amd64-3.6\spams
  copying spams\__init__.py -> build\lib.win-amd64-3.6\spams
  creating build\lib.win-amd64-3.6\spams_wrap
  copying spams_wrap\spams_wrap.py -> build\lib.win-amd64-3.6\spams_wrap
  copying spams_wrap\__init__.py -> build\lib.win-amd64-3.6\spams_wrap
  running egg_info
  writing python_spams.egg-info\PKG-INFO
  writing dependency_links to python_spams.egg-info\dependency_links.txt
  writing requirements to python_spams.egg-info\requires.txt
  writing top-level names to python_spams.egg-info\top_level.txt
  reading manifest file 'python_spams.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'python_spams.egg-info\SOURCES.txt'
  copying spams_wrap\spams.h -> build\lib.win-amd64-3.6\spams_wrap
  copying spams_wrap\spams_wrap.cpp -> build\lib.win-amd64-3.6\spams_wrap
  creating build\lib.win-amd64-3.6\spams_wrap\decomp
  copying spams_wrap\decomp\decomp.h -> build\lib.win-amd64-3.6\spams_wrap\decomp
  copying spams_wrap\decomp\lsqsplx.h -> build\lib.win-amd64-3.6\spams_wrap\decomp
  copying spams_wrap\decomp\projsplx.h -> build\lib.win-amd64-3.6\spams_wrap\decomp
  creating build\lib.win-amd64-3.6\spams_wrap\dictLearn
  copying spams_wrap\dictLearn\arch.h -> build\lib.win-amd64-3.6\spams_wrap\dictLearn
  copying spams_wrap\dictLearn\dicts.h -> build\lib.win-amd64-3.6\spams_wrap\dictLearn
  creating build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\cblas_alt_template.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\cblas_defvar.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\cblas_template.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\linalg.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\list.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\mexutils.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\misc.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  copying spams_wrap\linalg\utils.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
  creating build\lib.win-amd64-3.6\spams_wrap\prox
  copying spams_wrap\prox\fista.h -> build\lib.win-amd64-3.6\spams_wrap\prox
  copying spams_wrap\prox\groups-graph.h -> build\lib.win-amd64-3.6\spams_wrap\prox
  copying spams_wrap\prox\mexgrouputils.h -> build\lib.win-amd64-3.6\spams_wrap\prox
  copying spams_wrap\prox\project.h -> build\lib.win-amd64-3.6\spams_wrap\prox
  copying spams_wrap\prox\surrogate.h -> build\lib.win-amd64-3.6\spams_wrap\prox
  copying spams_wrap\prox\svm.h -> build\lib.win-amd64-3.6\spams_wrap\prox
  running build_ext
  cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
  error: Command "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ispams_wrap -Ispams_wrap\linalg -Ispams_wrap\prox -Ispams_wrap\decomp -Ispams_wrap\dictLearn -IC:\ProgramData\Anaconda3\envs\python3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\Library\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\envs\python3\include -ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include -ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpspams_wrap/spams_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\spams_wrap/spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -Wunused-variable -Wno-uninitialized -m64 -fopenmp" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for python-spams
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\python3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\python-spams_31de6775be654c6691f857d4fb6a5893\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\python-spams_31de6775be654c6691f857d4fb6a5893\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-h89ob9oi\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\python3\Include\python-spams'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m0a4oobw\python-spams_31de6775be654c6691f857d4fb6a5893\
    Complete output (50 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\myscipy_rand
    copying myscipy_rand\myscipy_rand.py -> build\lib.win-amd64-3.6\myscipy_rand
    copying myscipy_rand\__init__.py -> build\lib.win-amd64-3.6\myscipy_rand
    creating build\lib.win-amd64-3.6\spams
    copying spams\spams.py -> build\lib.win-amd64-3.6\spams
    copying spams\__init__.py -> build\lib.win-amd64-3.6\spams
    creating build\lib.win-amd64-3.6\spams_wrap
    copying spams_wrap\spams_wrap.py -> build\lib.win-amd64-3.6\spams_wrap
    copying spams_wrap\__init__.py -> build\lib.win-amd64-3.6\spams_wrap
    running egg_info
    writing python_spams.egg-info\PKG-INFO
    writing dependency_links to python_spams.egg-info\dependency_links.txt
    writing requirements to python_spams.egg-info\requires.txt
    writing top-level names to python_spams.egg-info\top_level.txt
    reading manifest file 'python_spams.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'python_spams.egg-info\SOURCES.txt'
    copying spams_wrap\spams.h -> build\lib.win-amd64-3.6\spams_wrap
    copying spams_wrap\spams_wrap.cpp -> build\lib.win-amd64-3.6\spams_wrap
    creating build\lib.win-amd64-3.6\spams_wrap\decomp
    copying spams_wrap\decomp\decomp.h -> build\lib.win-amd64-3.6\spams_wrap\decomp
    copying spams_wrap\decomp\lsqsplx.h -> build\lib.win-amd64-3.6\spams_wrap\decomp
    copying spams_wrap\decomp\projsplx.h -> build\lib.win-amd64-3.6\spams_wrap\decomp
    creating build\lib.win-amd64-3.6\spams_wrap\dictLearn
    copying spams_wrap\dictLearn\arch.h -> build\lib.win-amd64-3.6\spams_wrap\dictLearn
    copying spams_wrap\dictLearn\dicts.h -> build\lib.win-amd64-3.6\spams_wrap\dictLearn
    creating build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\cblas_alt_template.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\cblas_defvar.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\cblas_template.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\linalg.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\list.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\mexutils.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\misc.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    copying spams_wrap\linalg\utils.h -> build\lib.win-amd64-3.6\spams_wrap\linalg
    creating build\lib.win-amd64-3.6\spams_wrap\prox
    copying spams_wrap\prox\fista.h -> build\lib.win-amd64-3.6\spams_wrap\prox
    copying spams_wrap\prox\groups-graph.h -> build\lib.win-amd64-3.6\spams_wrap\prox
    copying spams_wrap\prox\mexgrouputils.h -> build\lib.win-amd64-3.6\spams_wrap\prox
    copying spams_wrap\prox\project.h -> build\lib.win-amd64-3.6\spams_wrap\prox
    copying spams_wrap\prox\surrogate.h -> build\lib.win-amd64-3.6\spams_wrap\prox
    copying spams_wrap\prox\svm.h -> build\lib.win-amd64-3.6\spams_wrap\prox
    running build_ext
    cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
    error: Command "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ispams_wrap -Ispams_wrap\linalg -Ispams_wrap\prox -Ispams_wrap\decomp -Ispams_wrap\dictLearn -IC:\ProgramData\Anaconda3\envs\python3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\Library\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\envs\python3\include -IC:\ProgramData\Anaconda3\envs\python3\include -ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include -ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpspams_wrap/spams_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\spams_wrap/spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -Wunused-variable -Wno-uninitialized -m64 -fopenmp" failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\python3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\python-spams_31de6775be654c6691f857d4fb6a5893\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-m0a4oobw\\python-spams_31de6775be654c6691f857d4fb6a5893\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-h89ob9oi\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\python3\Include\python-spams' Check the logs for full command output.

**Comment by samuelstjean** [comment]
well it's more of a build error than anything, but the premade version is here https://pypi.org/project/spams-bin/, normally also working for windows.

**Comment by Troudi-Abir** [comment]
Didn't work with me! any other solutions please?

**Comment by samuelstjean** [comment]
I guess scilpy is looking for the true package, even if the import is the same, try removing the line specifying the dependency (or change it to require spams-bin) from the setup and reinstall it.
