### ISSUE TITLE
RAM issues when returning the regularization path

### ISSUE THREAD

**Issue by alexandre-pasco** [samuelstjean/spams-python#25]
Hello,

When I use spams.lasso (and spams.omp) with return_reg_path=True, my RAM usage keeps increasing, and I don't get it back afterwise. So, by calling this function too often, my kernel crashes because of the RAM overconsumption. Do you have any ideas to solve this issue ? Thank you very much in advance.

The piece of code below shows the issue. I run it with python 3.9.15, spams 2.6.5.4, numpy 1.22.3 and psutil 5.9.0.

```
import psutil
import numpy as np
import spams

D = np.random.normal(size=(100, 1000))
D = D / np.linalg.norm(D, axis=0)
D = np.asfortranarray(D)
X = np.random.normal(size=(100, 100))
X = X / np.linalg.norm(X, axis=0)
X = np.asfortranarray(X)

for k in range(100):
    used_ram = psutil.virtual_memory().percent
    print(f'\rk:{k} used RAM:{used_ram}', end='')
    c, path = spams.lasso(X, D, lambda1=0, mode=2, return_reg_path=True)
```

**Comment by samuelstjean** [comment]
I'm not familiar with the internals, but we intend to close this here and merge everything in one unifying package, same with your other issue over at https://github.com/getspams/spams-python/issues/26, so it has a better chance of being fixed over there.
