### ISSUE TITLE
Problem with installing spams in windows (using pip)

### ISSUE THREAD

**Issue by Rabouali75** [samuelstjean/spams-python#32]
so i'm getting this error: 

> C:\Windows\System32>pip install spams
Collecting spams
  Using cached spams-2.6.5.4.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=1.0 in c:\program files\python39\lib\site-packages (from spams) (1.10.1)
Requirement already satisfied: numpy>=1.12 in c:\users\reabo\appdata\roaming\python\python39\site-packages (from spams) (1.24.2)
Requirement already satisfied: Pillow>=6.0 in c:\users\reabo\appdata\roaming\python\python39\site-packages (from spams) (9.4.0)
Building wheels for collected packages: spams
  Building wheel for spams (pyproject.toml) ... error
  error: subprocess-exited-with-error
  × Building wheel for spams (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\spams_wrap
      copying spams_wrap\spams_wrap.py -> build\lib.win-amd64-cpython-39\spams_wrap
      copying spams_wrap\__init__.py -> build\lib.win-amd64-cpython-39\spams_wrap
      creating build\lib.win-amd64-cpython-39\spams
      copying spams\spams.py -> build\lib.win-amd64-cpython-39\spams
      copying spams\__init__.py -> build\lib.win-amd64-cpython-39\spams
      creating build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\run.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\test_decomp.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\test_dictLearn.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\test_linalg.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\test_prox.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\test_spams.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\test_utils.py -> build\lib.win-amd64-cpython-39\spams\tests
      copying spams\tests\__init__.py -> build\lib.win-amd64-cpython-39\spams\tests
      creating build\lib.win-amd64-cpython-39\spams\data
      copying spams\data\boat.png -> build\lib.win-amd64-cpython-39\spams\data
      copying spams\data\lena.png -> build\lib.win-amd64-cpython-39\spams\data
      copying spams\version -> build\lib.win-amd64-cpython-39\spams
      running build_ext
      C:\Users\reabo\AppData\Local\Temp\pip-build-env-xazmk_yb\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py:535: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
        warnings.warn("Fallback spawn triggered. Please update distutils monkeypatch.")
      cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
      error: Command "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ispams_wrap -Ispams_wrap\linalg -Ispams_wrap\prox -Ispams_wrap\decomp -Ispams_wrap\dictLearn -IC:\Users\reabo\AppData\Local\Temp\pip-build-env-xazmk_yb\overlay\Lib\site-packages\numpy\core\include -IC:\Program Files\Python39\include -IC:\Program Files\Python39\include -IC:\Program Files\Python39\include -IC:\Program Files\Python39\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt /EHsc /Tpspams_wrap/spams_wrap.cpp /Fobuild\temp.win-amd64-cpython-39\Release\spams_wrap\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -Wunused-variable -Wno-uninitialized -m64" failed with exit status 2
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for spams
Failed to build spams
ERROR: Could not build wheels for spams, which is required to install pyproject.toml-based projects

Python version: 3.9.13
Also I installed spams-bin

**Comment by samuelstjean** [comment]
if you installed spams-bin and it worked, then you're good, it's a drop in replacement, or really the same thing with some config changes for modern computers.

**Comment by samuelstjean** [comment]
considering the wheel file builds fine here I'll close this then since I'm not sure what was missing here
