### ISSUE TITLE
 error: command 'x86_64-linux-gnu-g++' failed with exit status 1

### ISSUE THREAD

**Issue by MinakamiMitori** [samuelstjean/spams-python#5]
a docker env on CentOS with python version of 3.6.8

**Comment by samuelstjean** [comment]
Well, I guess you are trying to compile the extension, can you tell which commands and version what are you using?

**Comment by MinakamiMitori** [comment]
I downloaded the tar package, and just pip install it

**Comment by MinakamiMitori** [comment]
and pip version is 19.3.1

**Comment by samuelstjean** [comment]
you'll also need a copy of blas/lapack (preferably openblas or the intel mkl I guess) and headers to compile, could be that

**Comment by MinakamiMitori** [comment]
thanks for your answer, after I had blas and lapack, pip successed, and sorry for my blind to find out  /usr/bin/ld: cannot find -llapack 
in error information
