### ISSUE TITLE
ERROR: Failed building wheel for spams

### ISSUE THREAD

**Issue by beantr96** [samuelstjean/spams-python#6]
I install python spams for Windows and get the following error. I have tried installing build tools visual studios but it could not be fixed
`Looking in indexes: https://test.pypi.org/simple/
Collecting spams
  Downloading https://test-files.pythonhosted.org/packages/4c/9f/710c1d07594ee434e5dd33632a07b62a1b5c25ad84e96c319dd498243fd7/spams-2.6.1.11.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 3.2 MB/s
Requirement already satisfied: numpy in c:\users\tuan\anaconda3\envs\teupy\lib\site-packages (from spams) (1.18.4)
Requirement already satisfied: scipy in c:\users\tuan\anaconda3\envs\teupy\lib\site-packages (from spams) (1.4.1)
Requirement already satisfied: six in c:\users\tuan\anaconda3\envs\teupy\lib\site-packages (from spams) (1.14.0)
Building wheels for collected packages: spams
  Building wheel for spams (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\tuan\anaconda3\envs\teupy\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TUAN\\AppData\\Local\\Temp\\pip-install-9zqlertv\\spams\\setup.py'"'"'; __file__='"'"'C:\\Users\\TUAN\\AppData\\Local\\Temp\\pip-install-9zqlertv\\spams\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\TUAN\AppData\Local\Temp\pip-wheel-skcrhsoy'
       cwd: C:\Users\TUAN\AppData\Local\Temp\pip-install-9zqlertv\spams\
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying spams.py -> build\lib.win-amd64-3.6
  copying spams_wrap.py -> build\lib.win-amd64-3.6
  copying myscipy_rand.py -> build\lib.win-amd64-3.6
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  building '_spams_wrap' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ispams\linalg -Ispams\prox -Ispams\decomp -Ispams\dictLearn -Ic:\users\tuan\anaconda3\envs\teupy\lib\site-packages\numpy\core\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Users\TUAN\Anaconda3\Library\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpspams_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -fopenmp -Wunused-variable -m64
  cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ispams\linalg -Ispams\prox -Ispams\decomp -Ispams\dictLearn -Ic:\users\tuan\anaconda3\envs\teupy\lib\site-packages\numpy\core\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Users\TUAN\Anaconda3\Library\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpspams_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -fopenmp -Wunused-variable -m64" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for spams
  Running setup.py clean for spams
Failed to build spams
Installing collected packages: spams
    Running setup.py install for spams ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tuan\anaconda3\envs\teupy\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TUAN\\AppData\\Local\\Temp\\pip-install-9zqlertv\\spams\\setup.py'"'"'; __file__='"'"'C:\\Users\\TUAN\\AppData\\Local\\Temp\\pip-install-9zqlertv\\spams\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TUAN\AppData\Local\Temp\pip-record-naz4y6p_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tuan\anaconda3\envs\teupy\Include\spams'
         cwd: C:\Users\TUAN\AppData\Local\Temp\pip-install-9zqlertv\spams\
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying spams.py -> build\lib.win-amd64-3.6
    copying spams_wrap.py -> build\lib.win-amd64-3.6
    copying myscipy_rand.py -> build\lib.win-amd64-3.6
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building '_spams_wrap' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ispams\linalg -Ispams\prox -Ispams\decomp -Ispams\dictLearn -Ic:\users\tuan\anaconda3\envs\teupy\lib\site-packages\numpy\core\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Users\TUAN\Anaconda3\Library\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpspams_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -fopenmp -Wunused-variable -m64
    cl : Command line error D8021 : invalid numeric argument '/Wunused-variable'
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ispams\linalg -Ispams\prox -Ispams\decomp -Ispams\dictLearn -Ic:\users\tuan\anaconda3\envs\teupy\lib\site-packages\numpy\core\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Users\TUAN\Anaconda3\Library\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -Ic:\users\tuan\anaconda3\envs\teupy\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpspams_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\spams_wrap.obj -DNDEBUG -DUSE_BLAS_LIB -std=c++11 -fPIC -fopenmp -Wunused-variable -m64" failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tuan\anaconda3\envs\teupy\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TUAN\\AppData\\Local\\Temp\\pip-install-9zqlertv\\spams\\setup.py'"'"'; __file__='"'"'C:\\Users\\TUAN\\AppData\\Local\\Temp\\pip-install-9zqlertv\\spams\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TUAN\AppData\Local\Temp\pip-record-naz4y6p_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tuan\anaconda3\envs\teupy\Include\spams' Check the logs for full command output.`

**Comment by samuelstjean** [comment]
Looks like something maybe changed in the setup with recent numpy version, you could try asking upstream or the conda forge guys, maybe they fixed it or have a simple fix

http://spams-devel.gforge.inria.fr/downloads.html
https://github.com/conda-forge/python-spams-feedstock

My version for windows is the official one from python 2.7 with newer libs + a bunch of precompiled versions, if you get it working on windows for py3 I could probably add it. Didn't have much success last time I tried messing with compiler paths though.

**Comment by RaminNateghi** [comment]
I need to install spams-python in Kaggle kernel, The easiest way to install it is to have an .whl file. but Kaggle platform only supports the cp37 version.
how can I access to following wheel file?
(spams-2.6-cp37-cp37m-linux_x86_64.whl)

**Comment by samuelstjean** [comment]
You can also just try to install it from the source directly, it will then build the wheel file and install that afterwards.

**Comment by samuelstjean** [comment]
I am trying to get some newer builds running, this archive should contain the one you need 
https://github.com/samuelstjean/spams-python/suites/854055503/artifacts/9766175

I'll probably put them online officially once everything is working nice.

**Comment by samuelstjean** [comment]
See https://github.com/samuelstjean/spams-python/releases/tag/v2.6.1 to grab the files you need.
